kind: pipeline
type: kubernetes
name: default

steps:
- name: backend
  image: golang
  commands:
  - go version

- name: frontend
  image: node
  commands:
  - npm -v

- name: backend-2
  image: golang
  commands:
  - go version

- name: backend-3
  image: golang
  commands:
  - go version
